### PR TITLE
Close Workfiles window on Open

### PR DESCRIPTION
**Pull request by tokejepsen**
Fix for #544

### CODE REVIEW

**Comment by tokejepsen** [comment]
Seems to be some issues with coveralls and MacOS builds.

This PR is ready to merged otherwise.

**Comment by mkolar** [comment]
I'm happy with this

**Comment by BigRoy** [comment]
I did intentionally remove the behavior when I implemented the new tool as I used it much more to quickly browse and go between different scenes where having it open appeared faster to me. Nevertheless, I'm fine with closing on open - especially because it seems the preference for most people. 👍

**Comment by BigRoy** [comment]
> Just a note. This only changes the behavior of on_open_pressed, not on_browse_pressed.

That's actually a very good point. Maybe this is better placed in the `open_file` method of the Widget.

**Comment by tokejepsen** [comment]
> That's actually a very good point. Maybe this is better placed in the open_file method of the Widget.

Sure, we can do that!

**Comment by iLLiCiTiT** [comment]
+ I would add "action" to workfiles view which will allow to open workfile and keep window opened if @BigRoy need that?

**Comment by BigRoy** [comment]
> I would add "action" to workfiles view which will allow to open workfile and keep window opened if @BigRoy need that?

Not sure what you mean with Action? Do you mean a toggle somewhere, or a right mouse context menu?

Anyway, having the option to keep it open is no hard requirement for me. So I'd be happy to merge as is and potentially open an issue if it becomes a problem.

**Comment by iLLiCiTiT** [comment]
> Not sure what you mean with Action? Do you mean a toggle somewhere, or a right mouse context menu?

Sorry for ugliness.
image

**Comment by BigRoy** [comment]
Ah yes, I wouldn't bother. It wouldn't be very clear that that specific one would then **not** close the Window, right? 

For me this is ready to merge as is.

**Comment by BigRoy** [comment]
For what it's worth - just heard back from some Artists who also stated they "tend to keep it open" to quickly browse between different shots for some minor things. I'll create a separate issue to discuss a potential "toggle" to keep the tool open.

**Comment by davidlatwe** [comment]
If no other objections, merging this in one hour !

**Pull request merged**
