### PR TITLE
Add "ls" command to list projects in database.

### PR DESCRIPTION
**Pull request by tokejepsen**
This will list all projects in the database.

```bat
> python -u -m avalon.inventory --ls
Projects in database:
- batman
- myProject
```

### CODE REVIEW

**Comment by BigRoy** [comment]
@tokejepsen this looks good.

I'm not sure the changes on the _install_ lines are necessary, I liked the brief previous version which was just a single if statement. I believe it operates the same, so it's just cosmetics. Just wanted to point this out.

**Comment by mottosso** [comment]
Would it be possible to include some example output?

**Comment by tokejepsen** [comment]
Yup, sorry. Bit sloppy PR. Have updated the description.

**Comment by mottosso** [comment]
Haven't tested whether it technically works, but the tests pass so that's a good sign.

**Comment by tokejepsen** [comment]
Confirmed here, and its looks good to me visually.

**Pull request merged**
