### PR TITLE
Implement avalon style

### PR DESCRIPTION
**Pull request by BigRoy**
This adds an Avalon stylesheet (#293)

> Note that this is based on QDarkStyleSheet as discussed in the issue - I'm mentioning it here to ensure we check whether we would be safe regarding licensing. The files I have pushed here do **not** have any license information included.

Here's an example of the stylesheet on the project manager:
afbeelding

---

Currently the [application context manager in the tools lib](https://github.com/getavalon/core/compare/master...Colorbleed:style?expand=1#diff-592b29662f6fe9ce137804910b8f6bd5R25) automatically applies the stylesheet for new QApplication instances when running outside of software. As such the stylesheet is not applied if a QApplication is already running. If we were to apply the stylesheet to a running QApplication instance it would also apply it to e.g. Maya itself. To apply the stylesheet to the windows or dialogs themselves we'll need to apply the stylesheet on the widgets themselves instead of the application.

### CODE REVIEW

**Comment by BigRoy** [comment]
The massive list of Hound errors above are on compiled resources files for Qt. I assume we should safely ignore those.

**Comment by mottosso** [comment]
Whop!

Yes, try adding an `ignore_file: ` section to `.hound.yml`

- https://houndci.com/configuration

It might not work with Python, but worth a go.

**Comment by mottosso** [comment]
Should we just merge this? :P

**Comment by BigRoy** [comment]
> Currently the application context manager in the tools lib automatically applies the stylesheet for new QApplication instances when running outside of software. As such the stylesheet is not applied if a QApplication is already running. If we were to apply the stylesheet to a running QApplication instance it would also apply it to e.g. Maya itself. To apply the stylesheet to the windows or dialogs themselves we'll need to apply the stylesheet on the widgets themselves instead of the application.

What did you think of this? When and where would you like to apply the stylesheet?

**Comment by mottosso** [comment]
Oh, I see. We can just apply it to the window of each tool. That should be straightforward enough. In the show function.

**Comment by BigRoy** [comment]
That should cover it. The hound is shouting about the same old things which shouldn't be an actual problem. @mottosso should we merge like this?

**Comment by mottosso** [comment]
@BigRoy Yes

**Pull request merged**
