### PR TITLE
Nuke workflow

### PR DESCRIPTION
**Pull request by tokejepsen**
This is a work-in-progress PR for Avalon integration with Nuke.

Initially the ```Avalon``` menu is implemented.

### CODE REVIEW

**Comment by BigRoy** [comment]
Has anyone been able to play around some more? Maybe @mkolar?

**Comment by tokejepsen** [comment]
For an initial Nuke integration this might actually be enough.
It's got the menu and the tools have been tested to work. The rest of the workflow is in the configs.

**Comment by BigRoy** [comment]
Without `ls()` being implemented it could never list any loaded content, right? Which needs to be implemented in core.

Looks like a fine draft start - yet it'd need slightly more for all the tools to work. Fine to merge for me as long as we remember it need continued development for production.

**Comment by tokejepsen** [comment]
I don't have time unfortunately to continue with this development until 6 months from now.

I have added a commit that raises errors when trying to use ```containerize()``` and ```ls()``` so it should be obvious to anyone picking up the gauntlet.

**Comment by tokejepsen** [comment]
Closed in favour of #370

**Pull request closed without merging**
