### PR TITLE
Fix mayapy launch erroring on main window during on_init(), implement launching cbloader in active context, only containerize if any nodes are actually loaded by a loader, and minor other things

### PR DESCRIPTION
**Pull request by BigRoy**
This is implements a couple of changes, I'll briefly describe them all:

1. In the instance creator the family name is now **always** prefixed before the subset name.

_Related to:_ #278 

instance_creator

The subset field does not require typing the family name in front anymore, but this is enforced in the creator. The bottom field will display the final name, and you can type your specific subset's name, e.g. "default".

> Note: The subset name's first letter is always uppercased, even if you type "default" in the field for a model family it will become `modelDefault`. (This is also visible in the bottom field)

Additionally it also supports a little dropdown (button to the right of the subset field) to select an already existing subset name within that family within that asset, so for `character` it would for example show "Default" if `modelDefault` was already published before.

2. The `avalon.tools.cbloader` can now launch within the current context.

Whenever working in the asset `character` it will now upon launch show that specific asset. For example when you're working in the lighting for shot 010 and you open the launcher it will open up inside that specific shot, so should most likely display the published subsets for that specific scene.

3. A fix is implemented for maya batch or mayapy failing on `on_init`.

In the initialization the code tried to find the maya main window, but in batch mode it didn't have that specific element and would error out. That specific case is now captured, implemented here: https://github.com/Colorbleed/core/blob/c7dbc9564c68d9b78cbe176851c7c8e8b7746f94/avalon/maya/pipeline.py#L667

4. `discover()` in `pipeline.py` will now ignore python files starting with underscore.

To quickly disable a loader or other plug-in you can prefix the file with an underscore and it will be ignored.

> Note: We also pushed the `os.path.isfile()` check until after the extension check just because that would reduce the amount of disk access (since the extension check wouldn't need disk access yet, whereas `os.path.isfile` would.) That was purely an optimization choice aside of it just making more sense to me too.

5. After loading in host Maya the `containerize` is only triggered if the loader stored any nodes within itself, so an empty container would never be created.

> Note: as far as I know this should be backwards compatible in the way that I believe no loaders were ever intended to create empty containers in the scene. If instead they were, this might break backwards compatibility.

### CODE REVIEW

**Comment by mottosso** [comment]
Looks good!

image

This needs work. It isn't clear what the user is asked to type in. Is `default` automatically titlecased to `modelDefault`? Is `default` the subset itself? If so, what is it?

How about a horizontal layout?

```
 _______   _________   ___
|       | |         | |   |
| model | | Default | | v |
|_______| |_________| |___|
```

Where the `model` textbox is disabled, indicating that it will bear the name of the selected family, and `Default` is the editable final suffix to that name, defaulting to `Default` or whatever makes sense for the family.

**Comment by BigRoy** [comment]
I noticed just now that the `load` method in host has a lot of different return types, it currently returns a `list` on `OSError`, `None` when no nodes were loaded and a `str` when containerized with `containerise`. 

This might be somewhat confusing, but was already a problem before (where it would return either an empty list or a string).

---

> This needs work. It isn't clear what the user is asked to type in. Is default automatically titlecased to modelDefault? Is default the subset itself? If so, what is it?

Yes, this is true. The bottom field is "non-editable" there. We could style it differently so it's more clear. We decided to keep it enabled and set it to read only so that if you wanted to copy paste the text there you could.

The text at the bottom is the full subset name as it will end up after publishing.

> How about a horizontal layout?

That could work too, but it should still be clear the left field is **not** editable. I believe the problem then is still the same, it's requires a clearer styling for that.

This would also require when typing in the right field that it automatically changes the first letter to an uppercase as the user types. For me both sounds fine, and I think the current situation, though with the bottom field clarified, could work at least as well if not better. Feel free to bring up some more arguments. :)

**Comment by mottosso** [comment]
> For me both sounds fine, and I think the current situation, though with the bottom field clarified, could work at least as well if not better

Ah, ok. Yes in that case I think simply disabling the bottom one (which would cause it to draw with a greyish low-contrast color) should suffice.

Nice work!

**Comment by mottosso** [comment]
Or even make it just a label, without the surrounding box. To really drive the point home that it is non-editable and just for show.

**Comment by BigRoy** [comment]
I decided for now to just disable it, since it looked clearer then just swapping it with a QLabel. Now it looks like this:

afbeelding

Does this suffice for the time being?

**Comment by mottosso** [comment]
> Does this suffice for the time being?

For sure. Thanks for doing that.

**Comment by mottosso** [comment]
Code looks good too!

**Comment by mottosso** [comment]
Merge at will!

**Comment by BigRoy** [comment]
Actually, should we bump minor version?

**Comment by mottosso** [comment]
Versions aren't really being used at the moment so don't worry about it.
What is being used is the commit id,  for embedding the submodule in setup
distributions, and we'll get those regardless.

**Comment by BigRoy** [comment]
Cool, merging this now.

**Pull request merged**
