### PR TITLE
Simplify Loader and the arguments for `host.load`

### PR DESCRIPTION
**Pull request by BigRoy**
- Remove "preset" argument in `host.load`
- Remove "post_process" argument in `host.load`
- Add "data" argument in `host.load`; for additional settings of a loader

Note that already implemented Loaders in configs need to now also take in the "data" as argument into `Loader.process`.

### CODE REVIEW

**Comment by BigRoy** [comment]
Maybe the `data` argument is more descriptive when named `options`?

**Comment by aardschok** [comment]
I would opt for the argument to be called `options` as `options` can do something with the `data` but `data` can't do anything with the `options` ( hope this is a clear argumentation ).

**Comment by BigRoy** [comment]
> I would opt for the argument to be called options as options can do something with the data but data can't do anything with the options ( hope this is a clear argumentation ).

Not really; when refactoring it to `options` there is no more `data` in that local sense. :)

**Comment by BigRoy** [comment]
@mottosso what do you think?

**Comment by mottosso** [comment]
Looks good, let's do it.

**Pull request merged**
