### PR TITLE
Introduce switch logic

### PR DESCRIPTION
**Pull request by aardschok**
* Introduces switch logic for #310 
* Moved assertion up to ensure it works as intended
* Import `switch` and add it to __all__

Example code to test function where we have a scene with only the asset hero loaded

```python
import avalon.io as io
import avalon.api as api

host = api.registered_host()

# Example 1:
# Swap subset modelDefault of hero for modelLod0 of hero
asset = io.find_one({"type": "asset", "name": "hero"})
subset = io.find_one({"type": "subset", 
                      "name": "modelLod0",
                      "parent": asset["_id"]})

version = io.find_one({"type": "version", 
                       "parent": subset["_id"]},
                        sort=[('name', -1)])

representation = io.find_one({"type": "representation", "parent": version["_id"]})

container = list(host.ls())[0]
api.switch(container, representation)


# Example 2:
# Scene contains model of hero but model needs to be of villain
asset = io.find_one({"type": "asset", "name": "villain"})
subset = io.find_one({"type": "subset", "name": "modelDefault",
                      "parent": asset["_id"]})

version = io.find_one({"type": "version", 
                       "parent": subset["_id"]},
                      sort=[('name', -1)])

representation = io.find_one({"type": "representation",
                              "parent": version["_id"]})

container = list(host.ls())[0]

api.switch(container, representation)
```

### CODE REVIEW

**Comment by BigRoy** [comment]
This looks good. Just to be sure, this is functional - right? All that's needed is to implement a `switch` method on the Loader classes that the studio's  configuration has implemented, correct?

--- 

Aside from that, I think the next step is to have one of the tools expose this switch functionality to the artist. Which is slightly more involved and could maybe become a PR of its own to keep this one lightweight? @mottosso what do you think?

**Comment by aardschok** [comment]
> Just to be sure, this is functional - right?

Yes it is functional, as you said, a `switch` method is needed in a Loader in order to make it work.

**Comment by aardschok** [comment]
Here is an example of how it can work. You can fill in all three of the fields to switch to a specific representation.

Switch

**Comment by mottosso** [comment]
Kick ass :D

**Comment by BigRoy** [comment]
This is magic. I believe this is mergable. :muscle:

**Comment by BigRoy** [comment]
Also, should we bump the minor version of Avalon? (I believe we haven't done that recently with other PRs).
I also noticed just now that the Avalon version is set to `5.0.0` - any reason it's already at 5?
Should we maybe bump this to 5.1.0 then?

@mottosso what do you think?

**Comment by mottosso** [comment]
Yeah it's semantic versioning and major version increments is for when it breaks backwards compatibility. That's how many times that has happened so far. Ideally it wouldn't happen so frequently, but I'd recommend we keep doing it as both a reminder and notifier for others using Avalon.

**Comment by BigRoy** [comment]
I bumped the minor version. I'd say, @aardschok, feel free to merge once the checks have passed.

**Pull request merged**
