### PR TITLE
Implement new Scene Inventory

### PR DESCRIPTION
**Pull request by BigRoy**
This PR implements a new Scene Inventory to replace the current "manager".

It currently looks like this:

scene_inventory

### Features

- Groups the same representations (asset/subset/version/representation) into a collapsible item. As such many of the same items are shown together.
- Manage versions or remove many items at once by selecting them simultaneously.
- Set a specific version for many items at once.
- Find the actual file on disk (by "exploring" it; currently windows-only)

### CODE REVIEW

**Comment by mottosso** [comment]
Thanks, what about the style, like the icons, is it included?

**Comment by BigRoy** [comment]
> Thanks, what about the style, like the icons, is it included?

Yes, this is the version as it runs in Maya. The icons are QtAwesome as which was already a vendor.

**Comment by BigRoy** [comment]
Also, feature note. To update **all** in the scene.

1. Open this Scene Inventory
2. Ctrl + A (to select all entries)
3. Right click -> update to latest

**Comment by BigRoy** [comment]
@mottosso let me know if you need anything changed prior to a merge.

**Comment by mottosso** [comment]
I'll give this a try in a few mins

**Comment by mottosso** [comment]
This works well.

One critique and I realise it'll be controversial so I'll try and explain it best I can.

image

I think we should remove this.

The reason is that, yes, it is convenient but it encourages users to use Windows Explorer as part of their workflow. Once we're at a stage where this won't be necessary - which we may already be at, and if not let's talk about what's missing - getting this convenience out of their hands can be tough and it will harm our ability to help them through pipeline means.

For example, deleting, renaming or moving assets can't happen from Explorer. With this function, I as an artist would expect that we've thought about what is made possible via the Explorer and facilitate me going there to make changes. It would break.

Copying assets and sending to another artist, or getting the directory path for use elsewhere are all handy features, which are also easily facilitated by pipeline tools, such as a "Copy path". In that case, we could do better than get the absolute path, but also include template information such that a path could be used by someone who isn't local and doesn't share the `{root}` drive, for example.

It also means we can collect statistics on what the user is doing, to gain a better understanding of used/unused features, and collect errors through Sentry in order to help them better.

**Comment by BigRoy** [comment]
> I think we should remove this.

Sure, it's currently there for debugging purposes. I'll remove it so we can merge.

**Comment by mottosso** [comment]
Ok, that was easier than expected. :) Good!

**Comment by mottosso** [comment]
How about a `AVALON_DEBUGGING` for things like that, so that we can still have our tools available to us while we develop?

**Comment by mottosso** [comment]
Or `AVALON_DEBUG`

**Comment by BigRoy** [comment]
> Or AVALON_DEBUG

Sounds like a good idea, but since the feature isn't cross-OS compatible for now I'll remove this particular one. It will also make the code slightly simpler.

---

Also, an additional question the `app` and `task` that are passed to the context I'm currently getting them through: 
```python
    data['app'] = os.environ.get("AVALON_APP", "")
    data['task'] = os.environ.get("AVALON_TASK", "")
```

Is that the way they should be retrieved? Or should I get these differently, e.g. through the api?
The code is near the top in `avalon.tools.cbsceneinventory.app`.

**Comment by mottosso** [comment]
> Is that the way they should be retrieved? Or should I get these differently, e.g. through the api?

That's the way to do it.

State is currently all in the environment. I think we should #189 (`Session()`) in mind for anything state-related. I see more and more use for it, especially for tests and the project generation I'm putting together now.

**Comment by BigRoy** [comment]
Should be ready to go! :)

**Comment by mottosso** [comment]
Small cosmetic tweak; could you convert the ' to "? The OCD in me twerks at the inconsistency. :)

**Comment by mottosso** [comment]
Hah, twerk is not the right word.

image

..or is it?

**Comment by BigRoy** [comment]
I see you twerking. Shall I replace all of the `'` to `"` to get you less twerky? Or specific ones?

**Comment by mottosso** [comment]
All of them please. Death to '

**Pull request merged**
